//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalSystems.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consulta
    {
        public int cs_id { get; set; }
        public string cs_nome { get; set; }
        public string cs_observacao { get; set; }
        public byte cs_turno { get; set; }
        public System.DateTime cs_data { get; set; }
        public byte cs_situacao { get; set; }
        public int md_id { get; set; }
        public int pa_id { get; set; }
        public int co_id { get; set; }
    
        public virtual Convenio co_Convenios { get; set; }
        public virtual Medico md_Medicos { get; set; }
        public virtual Paciente pa_Pacientes { get; set; }
    }
}
