//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalSystems.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Convenio
    {
        public int co_id { get; set; }
        public string co_nome { get; set; }
        public string co_telefone { get; set; }
    }
}
