//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalSystems.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exame
    {
        public int ex_id { get; set; }
        public string ex_nome { get; set; }
        public string ex_observacoes { get; set; }
        public string ex_codigo { get; set; }
    }
}
