//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalSystems.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medico()
        {
            this.cs_Consulta = new HashSet<Consulta>();
        }
    
        public int md_id { get; set; }
        public string md_nome { get; set; }
        public string md_cpf { get; set; }
        public string md_crm { get; set; }
        public string md_endereco { get; set; }
        public int es_id { get; set; }
        public string cidade_descricao { get; set; }
        public int md_atendimentos_turnos { get; set; }
        public int esp_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Consulta> cs_Consulta { get; set; }
        public virtual Estado es_Estados { get; set; }
        public virtual Especialidade esp_Especialidade { get; set; }
    }
}
