//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalSystems.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente
    {
        public int pa_id { get; set; }
        public string pa_nome { get; set; }
        public string pa_cpf { get; set; }
        public int es_id { get; set; }
        public string cidade_descricao { get; set; }
        public string pa_telefone { get; set; }
        public System.DateTime pa_data_aniversario { get; set; }
        public byte pa_sexo { get; set; }
        public int pl_id { get; set; }
    
        public virtual Plano pl_Planos { get; set; }
    }
}
